name: pcbuilder
description: A Flutter Application dedicated for PC enthusiasts who want to build their own custom Gaming machines.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_map: any
  font_awesome_flutter: 8.7.0
  flutter_redux: ^0.7.0
  url_launcher: ^5.7.10
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  firebase_storage: ^5.2.0
  flutter_spinkit: ^4.1.2
  provider: ^4.3.2
  circular_profile_avatar: ^1.0.6
  get_it: ^5.0.3
  timeago: ^2.0.29
  settings_ui: ^0.5.0
  fluttertoast: ^7.1.6
  image_picker: ^0.6.7+17
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  image_path: "assets/images/logo_image.png"

flutter_native_splash:
  image: assets/images/background.png
  color: "000000"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
